name: Build (Windows)

on:
  push:
    paths:
      - 'source/*'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache oneMKL
      id: cache-onemkl
      uses: actions/cache@v3
      with:
        path: C:\Program Files (x86)\Intel\oneAPI\mkl
        key: ${{ runner.os }}-onemkl-2022.2.0

    - name: Setup oneMKL
      if: steps.cache-onemkl.outputs.cache-hit != 'true'
      run: |
        curl -s -o onemkl.exe -L https://registrationcenter-download.intel.com/akdlm/IRC_NAS/18899/w_onemkl_p_2022.2.0.9563_offline.exe
        onemkl.exe -s -a --silent --eula accept

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Download Vector Class Library
      run: |
        curl -s -o vcl.zip -L https://github.com/vectorclass/version2/archive/refs/tags/v2.01.04.zip
        unzip -q vcl.zip
        mv version2*/ vectorclass

    - name: Setup Ninja
      run: pip install ninja

    - name: Setup LLVM
      shell: bash
      run: |
        curl -s -o llvm-win64.exe -LJO https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.2/LLVM-15.0.2-win64.exe
        7z x -ollvm llvm-win64.exe

    - name: Configure
      shell: bash
      run: cmake -S . -B build -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_COMPILER="$(pwd)/llvm/bin/clang++.exe"
        -D CMAKE_CXX_FLAGS="-Wall -mavx2 -mfma -ffast-math"
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        -D MKL_DIR="/c/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/cmake/mkl"
        -D MKL_LINK=static -D MKL_THREADING=sequential -D MKL_INTERFACE=lp64
        -D VCL_HOME="$(pwd)/vectorclass"
        -D VS_INCLUDE_DIR="$(pwd)/vapoursynth/include"

    - name: Build
      run: cmake --build build --verbose

    - name: Install
      run: |
        cmake --install build --prefix install
        mkdir artifact
        copy install\bin\wnnm.dll artifact\

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: wnnm-windows-x64
        path: artifact

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: |
        cd artifact

        mkdir VapourSynth-WNNM-${{ github.event.inputs.tag }}
        7z a -t7z -mx=9 ../VapourSynth-WNNM-${{ github.event.inputs.tag }}.7z wnnm.dll

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: VapourSynth-WNNM-${{ github.event.inputs.tag }}.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
